# Generated by Django 4.0.4 on 2022-05-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tovo_website', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
    ]
